// Seed courts. Same fixture data the app used to ship as frontend mock data.
export const courts = [
  {
    id: 'court-1',
    name: 'Riverside Park Courts',
    location: '123 Riverside Dr',
    surface: 'Hard',
    indoor: false,
    numberOfCourts: 4,
    pricePerHour: 12,
    openHour: 7,
    closeHour: 21,
  },
  {
    id: 'court-2',
    name: 'Greenwood Tennis Club',
    location: '45 Greenwood Ave',
    surface: 'Clay',
    indoor: false,
    numberOfCourts: 6,
    pricePerHour: 18,
    openHour: 6,
    closeHour: 22,
  },
  {
    id: 'court-3',
    name: 'Downtown Indoor Courts',
    location: '900 Main St',
    surface: 'Hard',
    indoor: true,
    numberOfCourts: 3,
    pricePerHour: 25,
    openHour: 8,
    closeHour: 23,
  },
  {
    id: 'court-4',
    name: 'Maple Heights Community Courts',
    location: '77 Maple Heights Rd',
    surface: 'Hard',
    indoor: false,
    numberOfCourts: 2,
    pricePerHour: 8,
    openHour: 7,
    closeHour: 20,
  },
  {
    id: 'court-5',
    name: 'Lakeside Grass Club',
    location: '10 Lakeside Ln',
    surface: 'Grass',
    indoor: false,
    numberOfCourts: 2,
    pricePerHour: 22,
    openHour: 8,
    closeHour: 19,
  },
];
